### ISSUE TITLE
crafting page doesnt show numbers

### ISSUE THREAD

**Issue by kidofcubes** [craftygg/issues#1]
no numbers in the output slot of the crafting recipes page when there should be
![DA075C40-E0D6-4C0D-A0CC-C7D9DD898BE2](https://user-images.githubusercontent.com/40485669/127182150-cce5bb72-0906-43ea-b733-9391f7ac4574.jpeg)

**Comment by treboryx** [comment]
@ChineseMarc @talle117 is this an issue at all?

**Comment by ChineseMarc** [comment]
More like feature request, already added
