### ISSUE TITLE
Article page with different language selected doesn't exist ;/

### ISSUE THREAD

**Issue by Ali-Joon** [craftygg/issues#10]
![image](https://user-images.githubusercontent.com/48525075/147874301-001b37ca-ae75-4a14-ae05-61b0e4f0944f.png)
I don't think more context is needed anyway

**Comment by treboryx** [comment]
Hi @Ali-Joon!

Thanks for reporting this. I'll look into it.

**Comment by treboryx** [comment]
This has been fixed! Thanks for reporting!
