### ISSUE TITLE
Returning after visiting a player page causes previous players shown not appear

### ISSUE THREAD

**Issue by Ali-Joon** [craftygg/issues#11]
https://user-images.githubusercontent.com/48525075/159125285-c3350b54-b78a-472a-aa33-8b1bc4b149f3.mp4

So let me explain what happened in the video:
After scrolling down a bit, crafty URL changes (for example, to `/players?page=1`) which is normal
I've seen even if I don't scroll down and choose one of the first few players on the page, the URL still changes to load the second page
But either way, after returning to that profile (to the `/players?page=1`), the page wants to load the next page already
And the **wired part (the bug) is the players on the previous page will be not shown** *(I did it twice. First time, dikifi was in the top, but didn't appear after returning. The second time was the same for AmoSlowz)*

**Comment by ChineseMarc** [comment]
Thank you for reporting this,
There are two ways we can fix this:
One is to load all pages (might be a bit slow and not user friendly)
Other is to ask user what to do (popup/modal asking if you want to continue from page where you left off or reset to first page)

**Comment by Ali-Joon** [comment]
Actually, the better way to do it is to separate the pages, so returning makes it easier to continue browsing.
Or else, you can just make it return to the top of the page showing the first results (regardless of what page you were looking at).

**Comment by treboryx** [comment]
The URL is a work in progress to support copy pasting and sharing what are you looking at with others, it is by no means ready, and what you have addressed is a known concern. 

Thank you.
