### ISSUE TITLE
missing recipes

### ISSUE THREAD

**Issue by kidofcubes** [craftygg/issues#2]
raw iron -> iron ingot
raw gold -> gold ingot
raw copper -> copper ingot
copper ore -> copper ingot
gold block -> gold ingot
iron block -> iron ingot
iron item -> iron nugget
gold item -> gold nugget
gold nugget -> gold ingot
iron nugget -> iron ingot
azure bluet -> light gray dye
oxeye -> light grey dye
grey dye + white dye -> light grey dye
white tulip -> light grey dye
wither rose -> black dye
cornflower -> blue dye
stick -> bowl
bamboo -> stick
sugarcane -> sugar
slime block -> slimeball
carrot + baked potato + mushroom + cooked rabbit + bowl -> rabbit stew
poppy -> red dye
rose bush -> red dye
red tulip -> red dye
beetroot -> red dye
purple dye + pink dye -> magenta dye
red dye + blue dye + white dye -> magenta dye
pink dye + red dye + blue dye -> magenta dye
allium -> magenta dye
lilac -> magenta dye
red dye + red dye -> pink dye
peony -> pink dye
pink tulip -> pink dye
blue dye + white dye -> light blue dye
blue orchid -> light blue dye
red dye + yellow dye -> orange dye
orange tulip -> orange dye
dandelion -> yellow dye
sunflower -> yellow dye
lily of the valley -> white dye
logs -> charcoal
diamond item + netherite ingot -> netherite item

missing ones ive found so far

**Comment by treboryx** [comment]
@talle117 Were these added in your latest commit?

**Comment by talle117** [comment]
All of these have been fixed, thank you for helping us @KidOfCubes!
