### ISSUE TITLE
[website] Add the "load more" button.

### ISSUE THREAD

**Issue by 1moita** [craftygg/issues#5]
Add the "load more" button instead of automatically loading more content into a list.

**Comment by roooque** [comment]
I think this hinder whoever is browsing the site.

**Comment by treboryx** [comment]
Hi. This section is for reporting issues. What you've come here with today is a suggestion. I would suggest submitting your suggestion through https://crafty.gg/feedback or reaching out on our discord and I would also suggest:

When making such an important website change-suggestion, it's good to provide some valid arguments as to why you think a user would have a much better experience using a 'load more' button.

Looking forward to your suggestion! Thank you!
