### ISSUE TITLE
Commands not working at all.

### ISSUE THREAD

**Issue by philipheindel** [craftygg/issues#8]
I was really excited to try out the Crafty bot, so I created a test Discord server to test it. I added the bot and gave it all of the necessary permissions, but nothing happens when I try to issue a command. The only thing it will respond do is if I @ it with no message.
![image](https://user-images.githubusercontent.com/24397421/143375021-6472b74d-3613-44c5-b604-4509e39c55e0.png)

**Comment by treboryx** [comment]
Hi there. Did you invite Crafty through https://crafty.gg/bot/invite ?

**Comment by treboryx** [comment]
Hi there. Just an update, we've discovered what the issue was (other users experienced it as well) and it has now been resolved.
